### ISSUE TITLE
[Chef 12] Support private recipes

### ISSUE THREAD

**Issue by sethvargo** [opscode/chef-rfc#25]
#### Support private recipes
 * **Breaks Backwards Compatibility? (Workstation):** No
 * **Breaks Backwards Compatibility? (Cookbooks):**  No
 * **User Benefit:** Medium
  * Short description of the benefit: Cookbook developers will be able compose recipes into smaller pieces, while declaring a "public" API of cookbooks that are permitted to be present in a `run_list`.
 * **Impact:** Server?
  * Short description of the impact: Not sure if there are server pieces that need to change for this to be implemented.

**Comment by mconigliaro** [comment]
It looks like this never made it to the style guide? FWIW, the only reason I'm a fan of this convention is that when you have a cookbook with a lot of recipes, it can be a pain to figure out which ones you actually need to include and in what order. The conclusion I've come to personally is that every "public" recipe should give you something useful, and the order you include them shouldn't matter.
