### ISSUE TITLE
Remove Cookbook Overlays in Chef 12.0

### ISSUE THREAD

**Issue by danielsdeleo** [opscode/chef-rfc#43]
Cookbook overlays are the feature where you can have the same cookbook multiple times in your cookbook path, and Chef assembles a combined cookbook by preferring the files from the places later in the cookbook_path over the ones earlier in the cookbook_path.

This feature has been deprecated for a very long time (since at least 0.10.something) with a very verbose warning in `knife cookbook upload`. It is also not supported by Chef Zero or `knife upload`.

/cc @opscode/client-engineers

**Comment by coderanger** [comment]
Did this happen?

**Comment by lamont-granquist** [comment]
dont think so?

**Comment by coderanger** [comment]
Should probably re-title this then :)

**Comment by danielsdeleo** [comment]
As an individual change, I don't know if this is RFC-sized, so I'm going to close this.
